Repository The-Cage-s-Farm/theCagesFam, pull requests merged in 2021-04, with the labels that each got.

#20 Feature/12
  CagesFarm/CagesFarm.xcodeproj/project.pbxproj
  CagesFarm/CagesFarm/Nodes/KeyboardNumber.swift
  CagesFarm/CagesFarm/Scene/Dresser/DresserKeyboard.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/PuzzleScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Artboard.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Artboard@2x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Artboard@3x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Group 7.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Group 7@2x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/comoda_fechada/comoda_fechada.imageset/Group 7@3x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/teclado-matricial.imageset/teclado_matricial.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/teclado-matricial.imageset/teclado_matricial@2x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/teclado-matricial.imageset/teclado_matricial@3x.png
Labels: enhancement

#23 info.plist App Uses Non-Exempt Encryption e deleção de asset de dialg…
  CagesFarm/CagesFarm.xcodeproj/project.pbxproj
  CagesFarm/CagesFarm/Shared/Assets.xcassets/DialogBoxMock.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/DialogBoxMock.imageset/Contents 3.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/DialogBoxMock.imageset/Contents 4.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/DialogBoxMock.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/DialogBoxMock.imageset/Image.png
  CagesFarm/CagesFarmUITests/Info.plist
Labels: bug

#25 Interrupter's scene prototype 01
  CagesFarm/CagesFarm.xcodeproj/project.pbxproj
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/Interrupter/InterrupterScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/PuzzleScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
Labels: enhancement

#27 removendo alertas do swift lint
  CagesFarm/CagesFarm/Extensions/Images.swift
  CagesFarm/CagesFarm/Nodes/DialogueBox.swift
  CagesFarm/CagesFarm/Nodes/FaceCharacters.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
Labels: bug

#28 Habilita botão de fim de jogo
  CagesFarm/CagesFarm/Scene/Menu/MainMenuView.swift
  CagesFarm/CagesFarm/Scene/Menu/MenuViewController.swift
Labels: enhancement

#31 Feature/24 - Escritura e interruptor
  CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/Interrupter/InterrupterScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/OpenedTrunkScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/PuzzleScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_18.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_18.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_18.imageset/tony_getting_up_sprite_19.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_19.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_19.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_19.imageset/tony_getting_up_sprite_20.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_20.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_20.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_20.imageset/tony_getting_up_sprite_21.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_21.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_21.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_21.imageset/tony_getting_up_sprite_22.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_22.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_22.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_22.imageset/tony_getting_up_sprite_23.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_23.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_23.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_23.imageset/tony_getting_up_sprite_24.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_24.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_24.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/tony_getting_up/tony_getting_up_sprite_24.imageset/tony_getting_up_sprite_25.png
Labels: enhancement

#35 Starting scenes improvements
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/PuzzleScene.swift
Labels: bug

#34 [Refactor] - Refatorar código de GameViewController e MenuViewController.
  CagesFarm/CagesFarm/GameViewController.swift
  CagesFarm/CagesFarm/Scene/Menu/MenuViewController.swift
Labels: enhancement, good first issue

#37 bug fix dev
  CagesFarm/CagesFarm/Extensions/Images.swift
  CagesFarm/CagesFarm/Nodes/DialogueBox.swift
  CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
  CagesFarm/CagesFarm/Nodes/Inventory.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/Hall/HallScene.swift
  CagesFarm/CagesFarm/Shared/Assets.xcassets/Artboard.imageset/Artboard.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/Artboard.imageset/Artboard@2x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/Artboard.imageset/Artboard@3x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/Artboard.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/arrow.imageset/Contents 2.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/arrow.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/arrow.imageset/Image.png
Labels: bug

#39 Feature/26
  CagesFarm/CagesFarm/Extensions/Images.swift
  CagesFarm/CagesFarm/GameViewController.swift
  CagesFarm/CagesFarm/Nodes/DialogueBox.swift
  CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/Hall/HallScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
Labels: enhancement

#41 Corrige problema no baú e no teclado
  CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
  CagesFarm/CagesFarm/Scene/Dresser/DresserKeyboard.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/OpenedTrunkScene.swift
  CagesFarm/CagesFarm/Scene/PuzzleColors/PuzzleScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
Labels: enhancement

#43 walking
  CagesFarm/CagesFarm/Nodes/Characters.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/Hall/HallScene.swift
Labels: enhancement

#42 Refatora saída do quarto em um método próprio e corrige perspectiva do quadro
  CagesFarm/CagesFarm/Nodes/InteractableObjects.swift
  CagesFarm/CagesFarm/Scene/Dresser/DresserKeyboard.swift
  CagesFarm/CagesFarm/Scene/FirstScene/GameScene.swift
  CagesFarm/CagesFarm/Scene/SceneCoordinator.swift
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/Contents.json
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/Quadro com perspectiva clone-1.png-1.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/Quadro com perspectiva clone-1.png-2.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/Quadro com perspectiva clone-1.png.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/quadro_quarto.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/quadro_quarto@2x.png
  CagesFarm/CagesFarm/Shared/Assets.xcassets/QuadroPerspectiva.imageset/quadro_quarto@3x.png
Labels: bug
